<?php /** @var \Briqpay\Payments\Block\Order\View\BusinessCustomData $block */ ?>
<?php if ($block->hasBusinessCustomData()): ?>
    <div class="business-info-container">
        <span class="title">Company Information</span>

        <?php if ($block->getCompanyCin()): ?>
            <div>
                <strong>Company CIN:</strong> <?php echo $block->getCompanyCin(); ?>
            </div>
        <?php endif; ?>

        <?php if ($block->getCompanyName()): ?>
            <div>
                <strong>Company Name:</strong> <?php echo $block->getCompanyName(); ?>
            </div>
        <?php endif; ?>

        <?php if ($block->getCompanyVatNo()): ?>
            <div>
                <strong>Company VAT Number:</strong> <?php echo $block->getCompanyVatNo(); ?>
            </div>
        <?php endif; ?>
    </div>
<?php endif; ?>
